default_platform :ios

platform :ios do
  before_all do
    # cocoapods
  end

  lane :test do
    scan
  end

  lane :beta do

     # match(type: 'adhoc')
    
     # gym
    
     crashlytics(
       groups: "hardcoretap-test",
       notifications: true,
       ipa_path: "./HardcoreTap.ipa",
       api_token: "91cafb2b72a5d88bedb070de82e095b0ecd90caf",
       build_secret: "1c957528cc9da324f53eda599b1415444f67d1c9a7c2f8906bd2175abedf20c1"
     )
  end

  lane :release do
    match(type: 'appstore')
    capture_screenshots                  # generate new screenshots for the App Store
    sync_code_signing(type: "appstore")  # see code signing guide for more information
    gym(scheme: "HardcoreTap")
    upload_to_app_store    
  end

  after_all do |lane|
  end

  error do |lane, exception|
  end
end