default_platform :ios

platform :ios do
  before_all do
    cocoapods
  end

  lane :test do
    scan
  end

  lane :beta do    
     gym(scheme: "HardcoreTap")
  end

  lane :release do
    gym(scheme: "HardcoreTap")
    upload_to_app_store    
  end

end