platform :ios, '11.0'

target 'HardcoreTap' do

  use_frameworks!

  pod 'SwiftLint'
  pod 'R.swift'
  pod 'SwifterSwift'
  
  pod 'SnapKit'
  pod 'BonMot'

  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Performance'
  pod 'Firebase/AdMob'
  pod 'Fabric'
  pod 'Crashlytics'
  
  pod 'SwiftEntryKit'
#  pod 'Siren'
  pod 'NVActivityIndicatorView'
  pod 'IQKeyboardManagerSwift'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    # For Swift 4.2
    if ['NVActivityIndicatorView', 'SwifterSwift'].include? target.name
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.2'
      end
    end
  end
end
