target 'HardcoreTap' do

  use_frameworks!

  pod 'Firebase'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Performance'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'SwiftMessages'
  pod 'Siren'
  #pod 'Google-Mobile-Ads-SDK'

end
