platform :ios, '11.0'

target 'HardcoreTap' do

  use_frameworks!

  pod 'Firebase'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Performance'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'SwiftMessages'
  pod 'Siren'
  pod 'NVActivityIndicatorView'
  pod 'SwiftLint'
  pod 'IQKeyboardManagerSwift'
  pod 'Firebase/AdMob'

end
