//
//  UIColor+OLYAdditions.swift
//
//  Generated by Zeplin on 11/11/17.
//  Copyright (c) 2017 __MyCompanyName__. All rights reserved.
//

import UIKit

extension UIColor {
    
    @nonobjc class var olyBlueBlue: UIColor {
        return UIColor(named: "blueBlue")!
    }
    
    @nonobjc class var olyRobinSEgg: UIColor {
        return UIColor(named: "robinSEgg")!
    }
    
    @nonobjc class var olyDarkSkyBlue: UIColor {
        return UIColor(named: "darkSkyBlue")!
    }
    
    @nonobjc class var olyYellowishGreen: UIColor {
        return UIColor(named: "yellowishGreen")!
    }
    
    @nonobjc class var olyLipstick: UIColor {
        return UIColor(named: "lipstick")!
    }
    
    @nonobjc class var olyBlueberry: UIColor {
        return UIColor(named: "blueberry")!
    }
}

