//
//  UIFont+OLYAdditions.swift
//
//  Generated by Zeplin on 11/11/17.
//  Copyright (c) 2017 __MyCompanyName__. All rights reserved. 
//

import UIKit

extension UIFont {

	@nonobjc class var olyTextStyle: UIFont {
		return UIFont(name: "OpenSansHebrew-Regular", size: 100.0)!
	}

	@nonobjc class var olyTextStyle2: UIFont {
		return UIFont(name: "OpenSans-SemiBold", size: 14.0)!
	}

	@nonobjc class var olyTextStyle3: UIFont {
		return UIFont(name: "OpenSans-Regular", size: 14.0)!
	}
}
