platform :ios, '13.0'

target 'HardcoreTap' do

  use_frameworks!

  pod 'SwiftLint'
  pod 'R.swift'
  pod 'SwifterSwift'
  pod 'BonMot'

  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Performance'
  pod 'Firebase/AdMob'
  pod 'Fabric'
  pod 'Crashlytics'
  
  pod 'SwiftEntryKit'
  pod 'NVActivityIndicatorView'
  pod 'IQKeyboardManagerSwift'

end
