platform :ios, '13.0'

target 'HardcoreTap' do

  use_frameworks!

  pod 'SwiftLint'
  pod 'R.swift'
  pod 'BonMot'  
  pod 'SwiftEntryKit'
  pod 'NVActivityIndicatorView'
  pod 'IQKeyboardManagerSwift'

end
